version: '3.8'

services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: PokeProject
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - ./data:/var/lib/mysql
